### ISSUE TITLE
Error: 401 unauthorized when attempting to login

### ISSUE THREAD

**Issue by burritosoftware** [whatk233/ddg-email-panel#10]
![image](https://github.com/whatk233/ddg-email-panel/assets/37681398/2be1a872-025f-4a87-a0d4-021b8d8029ce)
![image](https://github.com/whatk233/ddg-email-panel/assets/37681398/aa1d8b8b-0f1a-4c97-ba0e-c176b218bba9)

**Comment by whatk233** [comment]
I wasn't able to reproduce the issue in our hosted site, is there an error log in the terminal?

**Comment by burritosoftware** [comment]
No error log. This seems to be because it is asking for a captcha on the main website (which I don't think is implemented here)

**Comment by burritosoftware** [comment]
Could there be a possibility to allow for using an API key (the Authorization: Bearer token) instead of a normal login flow, similar to how Bitwarden does [here](https://bitwarden.com/help/generator/#tab-duckduckgo-3Uj911RtQsJD9OAhUuoKrz)?

**Comment by whatk233** [comment]
> Could there be a possibility to allow for using an API key (the Authorization: Bearer token) instead of a normal login flow, similar to how Bitwarden does [here](https://bitwarden.com/help/generator/#tab-duckduckgo-3Uj911RtQsJD9OAhUuoKrz)?

It's a great idea.

In fact, the login flow is to obtain this token.

**Comment by burritosoftware** [comment]
> It's a great idea.
> 
> In fact, the login flow is to obtain this token.

Yeah, I think it would be best to allow for setting the API key, alongside instructions to get it, or maybe a small userscript that will get it from the website. This way if the login flow changes, this should still work.

**Comment by whatk233** [comment]
👌

**Comment by burritosoftware** [comment]
This works great, thank you!
