### ISSUE TITLE
增加 docker 构建

### ISSUE THREAD

**Issue by cat0x1f** [whatk233/ddg-email-panel#7]
如题。
我自己糊了一个 [这个](https://github.com/cat0x1f/ddg-email-panel)，希望官方增加 docker 构建。

**Comment by whatk233** [comment]
不错的建议，看到你把相关配置都写好了，要不试着提交一个pr？

**Comment by cat0x1f** [comment]
但是数据持久化之类的还没弄。

**Comment by cat0x1f** [comment]
可以。但是我数据持久化还没弄。

**Comment by cat0x1f** [comment]
#8 大概……就是这样……？

（我还不熟悉git😂

**Comment by whatk233** [comment]
> #8 大概……就是这样……？
> 
> （我还不熟悉git😂

多谢，这样应该没什么问题，晚点我再详细看看

**Comment by whatk233** [comment]
已合并
